# Generated by Django 4.1.7 on 2023-03-29 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_run_board_delete_run2board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='web.board'),
        ),
    ]
